# Generated by Django 5.2.6 on 2025-09-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_product_delete_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
